### PR TITLE
fix: bump docker-java to 3.2.2

### PR DESCRIPTION
**Pull request by dnwe**
- use jenkins [bom](https://github.com/jenkinsci/bom) for
  dependency management
- bump jenkins.version to LTS to match jackson2-api required by
  docker-java
- add slf4j overrides to dependencyManagement to satisfy upperbounds
  enforcer

### CODE REVIEW

**Comment by dnwe** [comment]
Fixes https://github.com/jenkinsci/docker-plugin/issues/825

**Comment by dnwe** [comment]
These are the upstream changes:
https://github.com/docker-java/docker-java/compare/3.1.5...3.2.2

Nothing jumped out at me as likely to cause a compatibility issue for consuming plugins, but it would be good to get one or two signoffs from maintainers before merging

**Review by SauceMcFloss — APPROVED** [review]
do it

**Comment by ericcitaire** [comment]
Sorry for the delay.

I'd like to suggest an alternative implementation here : #12. Let me know what you think.

**Comment by ericcitaire** [comment]
Sorry for the delay.

I'd like to suggest an alternative implementation here : #12. Let me know what you think.

**Comment by dnwe** [comment]
@ericcitaire absolutely fine with me!
Thank you

**Pull request closed without merging**
