### PR TITLE
Use recent docker-java version

### PR DESCRIPTION
**Pull request by bguerin**
See jenkinsci/docker-plugin#714

### CODE REVIEW

**Comment by bguerin** [comment]
Dupe of #4

**Comment by ericcitaire** [comment]
Hi @bguerin 

I made another PR : https://github.com/jenkinsci/docker-java-api-plugin/pull/5 which uses docker-java 3.1.5.

I also enabled incrementals (see [documentation](https://github.com/jenkinsci/incrementals-tools/blob/master/README.md)).
You can find the resulting hpi [here](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/docker-java-api/3.1.5-rc11.59b91388afe6/).

**Comment by ericcitaire** [comment]
Incremental build is also available for [docker-plugin](https://repo.jenkins-ci.org/incrementals/io/jenkins/docker/docker-plugin/1.1.10-rc915.f7c9b174bfb4/), built from https://github.com/jenkinsci/docker-plugin/pull/777.

Please give it a try and let me know.

**Comment by ericcitaire** [comment]
I'm closing this since https://github.com/jenkinsci/docker-java-api-plugin/pull/5 has been merged.

**Pull request closed without merging**
